"""migr

Revision ID: 002554f83b21
Revises: 
Create Date: 2024-06-20 14:50:47.835637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002554f83b21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('answer')

    # ### end Alembic commands ###
